version: '3'
services:
  vilicus:
    build:
      context: ../
      dockerfile: deployments/dockerfiles/vilicus/dev/Dockerfile
    command: sh -c "go run cmd/migration/main.go && go run cmd/api/main.go"
    volumes:
        - "../:/go/src/github.com/edersonbrilhante/vilicus"