version: '3'
services:
  adminer:
    container_name: db_adminer
    image: adminer
    ports:
      - "8045:8080"
    logging:
      driver: "json-file"
      options:
        max-size: 10m
    networks:
      - vilicus_net