name: "Build Vilicus Images"

on: [push, pull_request]

jobs:
  test-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
     
      - name: Build Images
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 
          make update-images