sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.23.2
  DOCKER_CLIENT_TIMEOUT: 120
  COMPOSE_HTTP_TIMEOUT: 120

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - docker-compose -f deployments/docker-compose.yml up -d
  - curl -o /tmp/wait-for-it.sh https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
  - chmod +x /tmp/wait-for-it.sh

script: |-
  /tmp/wait-for-it.sh http://localhost:8040 -- curl --location --request POST http://localhost:8040/analysis --header 'Content-Type: application/json' --data-raw '{"image": "node"}'    

after_script:
  - docker-compose -f deployments/docker-compose.yml down

cache:
  directories:
  - docker_images