language: bash

sudo: required

services:
  - docker

stages:
  - build-images
  - push-images

jobs:
  include:
    - stage: build-images
      before_script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      script:         
        - make build-images
        - make build-preset-postgres
    - stage: push-images
      before_script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      script:       
        - make push-images
        - make push-preset-postgres