os: linux
dist: xenial
language: shell

services:
  - docker

stages:
  - name: update-images
    if: |
      branch = main OR \
      type == cron

jobs:
  include:
    - stage: update-images
      script:         
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - make update-images