os: linux
dist: xenial
language: shell

services:
  - docker

stages:
  - name: build-images
    if: |
      branch = main AND \
      type != cron
  - name: build-preset-postgres
    if: |
      branch = main

jobs:
  include:
    - stage: build-images
      script:         
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - make update-images
    - stage: build-preset-postgres
      script:         
        - travis_wait 600 sleep infinity &
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - make update-preset-images