name: "Build Vilicus Images"

on:
  push:
    branches:
      - main
      - feature/migrate-ci
  pull_request:
    branches:
      - main

jobs:
  update-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Docker login
        run: |
          echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
     
      - name: Build Registry Image
        run: |
          make build-registry-image
     
      - name: Build Clair Image
        run: |
          make build-clair-image
     
      - name: Build Anchore Image
        run: |
          make build-anchore-image
     
      - name: Build Trivy Image
        run: |
          make build-trivy-image
      
      - name: Build Vilicus Image
        run: |
          make build-vilicus-image

      - name: Push Images
        run: |
          make push-images